[2023-02-27 09:55:56,851] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_price_board.push_price_board scheduled__2023-02-25T09:00:00+00:00 [queued]>
[2023-02-27 09:55:56,865] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: get_price_board.push_price_board scheduled__2023-02-25T09:00:00+00:00 [queued]>
[2023-02-27 09:55:56,865] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-02-27 09:55:56,865] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-02-27 09:55:56,865] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-02-27 09:55:56,893] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): push_price_board> on 2023-02-25 09:00:00+00:00
[2023-02-27 09:55:56,899] {standard_task_runner.py:52} INFO - Started process 10373 to run task
[2023-02-27 09:55:56,904] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'get_price_board', 'push_price_board', 'scheduled__2023-02-25T09:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/get_price_dag.py', '--cfg-path', '/tmp/tmp_2q2zqd_', '--error-file', '/tmp/tmpaneisooo']
[2023-02-27 09:55:56,905] {standard_task_runner.py:80} INFO - Job 10: Subtask push_price_board
[2023-02-27 09:55:57,033] {task_command.py:369} INFO - Running <TaskInstance: get_price_board.push_price_board scheduled__2023-02-25T09:00:00+00:00 [running]> on host 5b61798a1106
[2023-02-27 09:55:57,156] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_price_board
AIRFLOW_CTX_TASK_ID=push_price_board
AIRFLOW_CTX_EXECUTION_DATE=2023-02-25T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-25T09:00:00+00:00
[2023-02-27 09:55:57,159] {logging_mixin.py:115} INFO - Failed to connect
[2023-02-27 09:55:57,159] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/get_price.py", line 13, in push_price_data
    cursor = con.cursor()
AttributeError: 'NoneType' object has no attribute 'cursor'
[2023-02-27 09:55:57,169] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=get_price_board, task_id=push_price_board, execution_date=20230225T090000, start_date=20230227T095556, end_date=20230227T095557
[2023-02-27 09:55:57,187] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task push_price_board ('NoneType' object has no attribute 'cursor'; 10373)
[2023-02-27 09:55:57,223] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-27 09:55:57,267] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
